---
# From https://vitepress.dev/guide/deploy#github-pages.
concurrency:
  cancel-in-progress: false
  group: 'pages'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v5'
      with:
        fetch-depth: null
    - name: 'Setup Node'
      uses: 'actions/setup-node@v6'
      with:
        cache: 'npm'
        cache-dependency-path: 'docs/package-lock.json'
        node-version: 24
    - name: 'Setup Pages'
      uses: 'actions/configure-pages@v4'
    - name: 'Install dependencies'
      run: 'npm ci'
      working-directory: 'docs'
    - name: 'Build with VitePress'
      run: 'npm run build'
      working-directory: 'docs'
    - name: 'Upload artifact'
      uses: 'actions/upload-pages-artifact@v3'
      with:
        path: 'docs/.vitepress/dist'
  deploy:
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    name: 'Deploy'
    needs: 'build'
    runs-on: 'ubuntu-latest'
    steps:
    - id: 'deployment'
      name: 'Deploy to GitHub Pages'
      uses: 'actions/deploy-pages@v4'
name: 'Deploy VitePress site to GitHub Pages'
'on':
  push:
    branches:
    - 'main'
permissions:
  contents: 'read'
  id-token: 'write'
  pages: 'write'
...
